const themes = {
  light: {
    primaryWhite: '#FFFFFF',
    primaryWhiteRGB: '255, 255, 255',
    backgroundBlue: '#F3FCFF',
    primaryLightBlue: '#7DB5F2',
    primaryBlue: '#68A0F3',
    primaryRed: '#F55464',
    primaryYellow: '#F7C500',
    primaryYellow: '#F7C500',
    primaryPurple: '#2F2E63',
    primaryDarkPurple: '#110E3C',
    primaryGreyPurple: '#b5aabb',

    fontSizeSmaller: 8,
    fontSizeSmall: 12,
    fontSizeMedium: 14,
    fontSizeDefault: 16,
    fontSizeLarge: 24,
    fontSizeBig: 32,
    fontSizeBigger: 48,
  },
  dark: {
    primaryWhite: '#FFFFFF',
    primaryWhiteRGB: '255, 255, 255',
    backgroundBlue: '#F3FCFF',
    primaryLightBlue: '#7DB5F2',
    primaryBlue: '#68A0F3',
    primaryRed: '#F55464',
    primaryYellow: '#F7C500',
    primaryYellow: '#F7C500',
    primaryPurple: '#2F2E63',
    primaryDarkPurple: '#110E3C',

    fontSizeSmaller: 8,
    fontSizeSmall: 12,
    fontSizeMedium: 14,
    fontSizeDefault: 16,
    fontSizeLarge: 24,
    fontSizeBig: 32,
    fontSizeBigger: 48,
  },
};

export default themes;
